[versions]
agp = "9.0.0-beta05"
espressoCore = "3.7.0"
junit = "4.13.2"
kotestAssertionsCore = "6.0.7"
kotlin = "2.3.0"
android-minSdk = "35"
android-compileSdk = "36"
runner = "1.7.0"
vanniktechMavenPublish = "0.35.0"
sonarqube = "7.2.2.6593"

[libraries]
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotestAssertionsCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }