[versions]
agp = "8.13.0"
espressoCore = "3.7.0"
junit = "4.13.2"
kotlin = "2.2.20"
android-minSdk = "35"
android-compileSdk = "36"
runner = "1.7.0"
vanniktechMavenPublish = "0.34.0"

[libraries]
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }