name: Test developing version
run-name: Test developing version of ${{ github.repository }} triggered by a ${{ github.event_name }} event.
on:
  pull_request:
    branches: [ dev ]
jobs:
  Test-Dev-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      KOTLIN_JS_USE_PLATFORM_PATHS: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Java 25
        run: echo "JAVA_HOME=$JAVA_HOME_25_X64" >> $GITHUB_ENV
      - name: Set up gradle
        run: ./gradlew -version
      - name: wasm Js Browser Test
        run: ./gradlew clean wasmJsBrowserTest
      - name: wasm Js Test
        run: ./gradlew clean wasmJsTest
      - name: linux X64 Test
        run: ./gradlew clean linuxX64Test
      - name: jvm Test
        run: ./gradlew clean jvmTest