name: Test developing version
run-name: Test developing version of ${{ github.repository }} triggered by a ${{ github.event_name }} event.
on:
  pull_request:
    branches: [ dev ]
jobs:
  Test-Dev-Actions:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Enabling Java."
      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'
          cache-dependency-path: | 
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties
      - run: echo "The ${{ github.repository }} repository being tested for wasm js browser."
      - run: ./gradlew clean wasmJsBrowserTest
      - run: echo "The ${{ github.repository }} repository being tested for wasm js."
      - run: ./gradlew clean wasmJsTest
      - run: echo "The ${{ github.repository }} repository being tested for linux X64."
      - run: ./gradlew clean linuxX64Test
      - run: echo "The ${{ github.repository }} repository being tested for jvm."
      - run: ./gradlew clean jvmTest
      - run: echo "This job's status is ${{ job.status }}."